development:
  adapter: postgresql
  database: prelunch_development
  host: localhost
test:
  adapter: postgresql
  database: prelunch_test
  host: localhost
production:
  adapter: postgresql
  database: prelunch_production
  username: root
  password: 
  host: localhost
